from cx_Freeze import setup, Executable
includefiles = ["back1.png", "back2.png", "brick.png", "brick2.png",
                "castle.png", "castle2.png", "castle8.png", "castle9.png",
                "end_turn1.png","end_turn1-2.png","end_turn2.png","end_turn2-2.png", 
                "elf.png", "elf2.png", "factory.png", "factory2.png", "fire.png",
                "fire2.png", "fog_of_war.png","fog_of_war2.png","fog_of_war3.png","fog_of_war4.png",
                "game_info1.png", "game_info2.png",
                "gather1.png", "gather2.png",
                "info_card.png","info_card2.png","info_card3.png","info_card4.png",
                "info_card5.png","info_card6.png","info_card7.png","info_card8.png",
                "lightning.png", "mine.png", "new_game1.png","lightning2.png", "mine2.png", "new_game2.png",
                "next1.png", "northpole.png", "options_menu1.png","next2.png", "northpole2.png", "options_menu2.png",
                "Play1.png", "present_bag.png", "reindeer.png","Play2.png", "reindeer2.png",
                "santa.png", "snow.png","snowfall_background2.png","santa2.png", "snow2.png","snowfall_background3.png",
                "start_menu.png", "take_turn1.png", "tree_cursor.png", "take_turn2.png",
                "wood.png", "wood2.png",
                "tut1.png", "tut2.png", "tut3.png", "tut4.png",
                "tut5.png", "tut6.png", "tut7.png", "tut8.png",
                "tut9.png", "tut10.png", "tut11.png", "tut12.png",
                "tut13.png", "tut14.png", "tut15.png", "tut16.png",
                "tut17.png", "tut18.png", "tut19.png",
                "audio2.wav", "audio3.wav", "audio4.wav", "audio5.wav",
                "audio6.wav", "audio7.wav", "audio8.wav", "audio9.wav",
                "audio10.wav", "audio11.wav", "audio12.wav", "audio13.wav",
                "audio14.wav", "audio15.wav", "audio16.wav", "audio17.wav",
                "audio18.wav", "audio19.wav", "audio20.wav", "audio21.wav",
                "audio22.wav", "audio23.wav", "audio24.wav"]
setup(name = "Arius",
      version = "2.0",
      description = "4Mahlon",
      options = {"build_exe": {"include_files":includefiles}},
      executables = [Executable("Arius.py")])
